"use client";
import "./globals.css";
import type { Metadata } from "next";
import { Source_Code_Pro } from "next/font/google";
import { CacheProvider } from "@chakra-ui/next-js";
import { ChakraProvider } from "@chakra-ui/react";
import "./scrollbar.css";
const sourceCodePro = Source_Code_Pro({ subsets: ["latin"] });

// export const metadata: Metadata = {
// 	title: "Khalil Collins",
// 	description: "Generated by create next app",
// };

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<>
			<html lang="en">
				<body className={sourceCodePro.className}>
					<CacheProvider>
						<ChakraProvider>{children} </ChakraProvider>
					</CacheProvider>
				</body>
			</html>
		</>
	);
}
